version: '3'

services:
  redis:
    image: redis:6-alpine
    restart: always
    container_name: redis
    command: redis-server --maxmemory {RAM_MB}mb --requirepass {PASSWORD}
    ports:
      - 6379:6379
