version: '3'

services:
  redis:
    image: redis:6-alpine
    restart: always
    container_name: redis
    command: redis-server --appendonly yes --requirepass {PASSWORD}
    volumes:
      - redis-data:/data
    ports:
      - 6379:6379

volumes:
  redis-data: